### ISSUE TITLE
templateの条件分岐がうまくいかない

### ISSUE THREAD

**Issue by YukiY727** [YukiY727/Twitter_clone#8]
#7 
でfollowの機能を実装していたのですが、
https://github.com/YukiY727/Twitter_clone/blob/377cb25f95a3d86a0404cc007f03c567714b72be/ttter/templates/accounts/user_page.html#L3-L11
の部分でfollowをしているにもかかわらず、「followする」が表示されてしまいます。
viewのほうで
https://github.com/YukiY727/Twitter_clone/blob/377cb25f95a3d86a0404cc007f03c567714b72be/ttter/accounts/views.py#L65-L66
printしているのですが、この部分は
```
[15/Aug/2022 10:07:57] "GET /accounts/userlist/ HTTP/1.1" 200 1190
True
[15/Aug/2022 10:07:59] "GET /accounts/1/user_page/ HTTP/1.1" 200 1242
```
でTrueでかえってきます。
解決策教えていただきたいです！

**Comment by tak848** [comment]
bool値なら
`{% if is_followed %}`
でどうでしょう？

ダメだったら，`{{ is_followed }}`と値をそのままテンプレートに描画してみてどうなるか教えてください！

**Comment by YukiY727** [comment]
すいません解決しました！
https://github.com/YukiY727/Twitter_clone/blob/377cb25f95a3d86a0404cc007f03c567714b72be/ttter/accounts/views.py#L65-L66
の上と下ののコードでfollowerとfollowee逆になってました
